import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Search, Plus, Users, Building2, BriefcaseBusiness, TrendingUp, Pencil, Trash2, Eye, X, ChevronLeft, ChevronRight, RefreshCw, CheckCircle2, AlertCircle, Mail, MapPin, Sparkles } from 'lucide-react';
import './styles.css';
import { api } from './lib/api';

const empty = { name:'', email:'', department:'Engineering', designation:'' };
const departments = ['All','Engineering','Design','Product','Marketing','Sales','HR','Finance'];

function App(){
 const [employees,setEmployees]=useState([]), [stats,setStats]=useState({total:0,departments:[]}), [search,setSearch]=useState(''), [department,setDepartment]=useState('All'), [page,setPage]=useState(1), [pages,setPages]=useState(1), [loading,setLoading]=useState(true), [error,setError]=useState(''), [modal,setModal]=useState(null), [form,setForm]=useState(empty), [saving,setSaving]=useState(false), [toast,setToast]=useState(null), [selected,setSelected]=useState(null), [online,setOnline]=useState(false);
 const limit=8;
 const load=async()=>{setLoading(true);setError('');try{const [list,st,h]=await Promise.all([api.list({search,department,page,limit}),api.stats(),api.health()]);setEmployees(list.data);setPages(list.pagination.pages);setStats(st.data);setOnline(h.database==='connected')}catch(e){setError(e.message);setOnline(false)}finally{setLoading(false)}};
 useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[search,department,page]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(null),3200);return()=>clearTimeout(t)}},[toast]);
 const deptCount=useMemo(()=>stats.departments?.length||0,[stats]);
 const openCreate=()=>{setForm(empty);setModal('create')};
 const openEdit=e=>{setForm({name:e.name,email:e.email,department:e.department,designation:e.designation});setSelected(e);setModal('edit')};
 const submit=async ev=>{ev.preventDefault();setSaving(true);try{if(modal==='create') await api.create(form); else await api.update(selected._id,form);setModal(null);setSelected(null);setToast({ok:true,text:modal==='create'?'Employee added successfully':'Employee updated successfully'});load()}catch(e){setToast({ok:false,text:e.message})}finally{setSaving(false)}};
 const remove=async e=>{if(!confirm(`Delete ${e.name}? This action cannot be undone.`))return;try{await api.remove(e._id);setToast({ok:true,text:'Employee removed'});if(selected?._id===e._id)setSelected(null);load()}catch(err){setToast({ok:false,text:err.message})}};
 return <div className="app">
  <aside className="sidebar"><div className="brand"><div className="brand-mark">G</div><div><b>GUPIO</b><span>PEOPLE OS</span></div></div><nav><button className="nav active"><Users size={18}/>Employees</button><button className="nav"><Building2 size={18}/>Departments</button><button className="nav"><BriefcaseBusiness size={18}/>Directory</button></nav><div className="side-bottom"><div className="status-dot"><i className={online?'online':''}></i><span>{online?'API & DB online':'API disconnected'}</span></div><small>Campus Drive • Full Stack</small></div></aside>
  <main className="main"><header className="top"><div><div className="eyebrow"><Sparkles size={14}/>Employee Intelligence</div><h1>People <em>Dashboard</em></h1><p>Manage your team, track departments and keep employee records in sync.</p></div><button className="primary" onClick={openCreate}><Plus size={18}/> Add employee</button></header>
   <section className="stats"><Stat icon={<Users/>} label="Total employees" value={stats.total}/><Stat icon={<Building2/>} label="Departments" value={deptCount}/><Stat icon={<TrendingUp/>} label="Top department" value={stats.departments?.[0]?stats.departments[0]._id:'—'} small/><Stat icon={<CheckCircle2/>} label="System status" value={online?'Healthy':'Offline'} good={online}/></section>
   <section className="workspace"><div className="toolbar"><div className="search"><Search size={18}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search by name or email..."/><kbd>⌘ K</kbd></div><select value={department} onChange={e=>{setDepartment(e.target.value);setPage(1)}}>{departments.map(d=><option key={d}>{d}</option>)}</select><button className="icon-btn" onClick={load} title="Refresh"><RefreshCw size={17}/></button></div>
    {error && <div className="error"><AlertCircle size={18}/><span>{error}</span><button onClick={load}>Retry</button></div>}
    <div className="table-card"><div className="table-head"><div><h2>Employee directory</h2><span>{stats.total} records · live database</span></div><div className="legend"><i></i> Synced</div></div>
      {loading?<div className="skeletons">{Array.from({length:6}).map((_,i)=><div className="skeleton" key={i}/>)}</div>:employees.length===0?<Empty onAdd={openCreate}/>:<div className="table-wrap"><table><thead><tr><th>Employee</th><th>Department</th><th>Designation</th><th>Joined</th><th className="actions">Actions</th></tr></thead><tbody>{employees.map(e=><tr key={e._id}><td><div className="person"><Avatar name={e.name}/><div><strong>{e.name}</strong><span>{e.email}</span></div></div></td><td><span className="pill">{e.department}</span></td><td>{e.designation}</td><td>{new Date(e.createdAt).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}</td><td className="actions"><button onClick={()=>setSelected(e)} title="View"><Eye size={17}/></button><button onClick={()=>openEdit(e)} title="Edit"><Pencil size={17}/></button><button className="danger" onClick={()=>remove(e)} title="Delete"><Trash2 size={17}/></button></td></tr>)}</tbody></table></div>}
      {!loading&&employees.length>0&&<div className="pagination"><span>Page {page} of {pages}</span><div><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={17}/></button><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}><ChevronRight size={17}/></button></div></div>}
    </div></section>
  </main>
  {modal&&<Modal title={modal==='create'?'Add employee':'Edit employee'} onClose={()=>setModal(null)}><form onSubmit={submit} className="form"><Field label="Full name" required><input autoFocus required minLength="2" maxLength="80" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. Priya Sharma"/></Field><Field label="Email" required><input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="name@company.com"/></Field><div className="grid2"><Field label="Department" required><select value={form.department} onChange={e=>setForm({...form,department:e.target.value})}>{departments.slice(1).map(d=><option key={d}>{d}</option>)}</select></Field><Field label="Designation" required><input required minLength="2" value={form.designation} onChange={e=>setForm({...form,designation:e.target.value})} placeholder="e.g. Software Engineer"/></Field></div><div className="form-actions"><button type="button" className="secondary" onClick={()=>setModal(null)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving...':modal==='create'?'Create employee':'Save changes'}</button></div></form></Modal>}
  {selected&&!modal&&<Modal title="Employee profile" onClose={()=>setSelected(null)}><div className="profile"><Avatar name={selected.name} large/><h2>{selected.name}</h2><p>{selected.designation}</p><div className="profile-grid"><Info icon={<Mail/>} label="Email" value={selected.email}/><Info icon={<Building2/>} label="Department" value={selected.department}/><Info icon={<MapPin/>} label="Record" value={new Date(selected.createdAt).toLocaleDateString('en-IN')}/></div><div className="form-actions"><button className="secondary" onClick={()=>setSelected(null)}>Close</button><button className="primary" onClick={()=>openEdit(selected)}><Pencil size={16}/> Edit employee</button></div></div></Modal>}
  {toast&&<div className={'toast '+(toast.ok?'success':'fail')}>{toast.ok?<CheckCircle2 size={18}/>:<AlertCircle size={18}/>} {toast.text}</div>}
 </div>
}
function Stat({icon,label,value,small,good}){return <div className="stat"><div className="stat-icon">{icon}</div><div><span>{label}</span><strong className={(small?'small ':'')+(good?'good':'')}>{value}</strong></div></div>}
function Avatar({name,large}){return <div className={'avatar '+(large?'large':'')}>{name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}</div>}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
function Info({icon,label,value}){return <div className="info"><div>{icon}</div><span>{label}</span><strong>{value}</strong></div>}
function Modal({title,onClose,children}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><div className="modal-head"><h2>{title}</h2><button onClick={onClose}><X size={20}/></button></div>{children}</div></div>}
function Empty({onAdd}){return <div className="empty"><div className="empty-icon"><Users size={28}/></div><h3>No employees found</h3><p>Try changing your search or add your first employee.</p><button className="primary" onClick={onAdd}><Plus size={17}/> Add employee</button></div>}

createRoot(document.getElementById('root')).render(<App/>);